name: flutter_clean_app_examples
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Network 
  dio: ^4.0.6  

  # State Management
  provider: ^6.0.3

  # Database
  hive_flutter: ^1.1.0  
  hive: ^2.2.2
  path_provider: ^2.0.11
  # Google
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0

  # Core Utiltity  
  flutter_dotenv: ^5.0.2

  cupertino_icons: ^1.0.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  hive_generator: ^1.1.3


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  