name: flutter_clean_app_examples
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Network 
  dio: ^4.0.6  

  # State Management
  provider: ^6.0.3

  # Core Utiltity  
  flutter_dotenv: ^5.0.2

  cupertino_icons: ^1.0.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  